webscopeio/license.sh

license_sh/helpers.py
tests/runners/test_helpers.py

fix: is_license_ok fixed for complex license

---

docs/README.md
docs/usage.md
license_sh/__main__.py
license_sh/commands/run_license_sh.py

feat: --config option added

---

license_sh/commands/run_license_sh.py

fix: check run after whitelisting

---

docs/usage.md

feat: prerequisites added

---

license_sh/runners/maven/__init__.py
license_sh/runners/runners_shared.py
license_sh/runners/yarn/__init__.py

feat: prerequisite check added

---

license_sh/runners/yarn/__init__.py
tests/runners/test_yarn.py

Fixed issue, hwere yarn had so many unresolved licenses

fix: yarn unknown licenses

---

docs/usage.md
license_sh/__main__.py
license_sh/commands/run_license_sh.py
license_sh/project_identifier/__init__.py

Added project option to be able to specified project in multi project directories

feat: added project option

---

license_sh/helpers.py

To be able to parse M AND I AND T and other funny licenses into correct one

feat: normalize before parsing

---

license_sh/helpers.py

fix: boolean error

---

license_sh/runners/npm/__init__.py

fix: check if dependency is present in lock file

---

license_sh/runners/maven/__init__.py
license_sh/runners/yarn/__init__.py

fix: yarn check for dependency presence

---

license_sh/helpers.py
tests/test_helpers.py

fix: npm version should have priority

---

license_sh/commands/run_license_sh.py
license_sh/helpers.py
license_sh/reporters/ConsoleReporter.py
tests/test_helpers.py

Added analyze_problem property if you are running under `--dependencies` flag. We still need to add some console output

feat: analyze_problem added

---

license_sh/__main__.py
license_sh/analyze/__init__.py
license_sh/analyze/analyze_shared.py
license_sh/analyze/maven.py
license_sh/analyze/pipenv.py
tests/analyze/test_pipenv.py

feat: python license text analyzer added

---

license_sh/helpers.py
license_sh/reporters/ConsoleReporter.py

Fixes hasattr issues

---

license_sh/analyze/analyze_shared.py
license_sh/analyze/maven.py
tests/analyze/test_analyze_shared.py

Maven license text are sometimes put as html pages. This will increase analyze percentage

feat: transform html added

---

license_sh/helpers.py
license_sh/reporters/ConsoleReporter.py
tests/test_helpers.py

fix: filter dependency tree based on value for presence

---

.github/workflows/python-build.yml
Pipfile
Pipfile.lock
docs/usage.md
license_sh/__main__.py
license_sh/analyze/__init__.py
license_sh/analyze/analyze_shared.py
license_sh/commands/run_license_sh.py
license_sh/config.py
license_sh/helpers.py
license_sh/reporters/ConsoleReporter.py
license_sh/runners/__init__.py
license_sh/runners/maven/__init__.py
license_sh/runners/npm/__init__.py
license_sh/runners/python/__init__.py
license_sh/runners/yarn/__init__.py
tests/test_helpers.py
tests/test_validations.py

Introduces `-i` flag. 
Runs without questions by default.

Interactive mode -i --interactive

---

license_sh/commands/run_license_sh.py

Deprecation has to be gradual. Labeled tree is in use in the code

fix: Label tree added back

---

license_sh/analyze/analyze_shared.py
license_sh/analyze/maven.py
license_sh/analyze/pipenv.py

fix: read error

---

license_sh/commands/run_license_sh.py

fix: ignorePackage

---

license_sh/analyze/analyze_shared.py
license_sh/analyze/maven.py
license_sh/commands/run_license_sh.py
license_sh/helpers.py
tests/analyze/test_analyze_shared.py
tests/analyze/test_maven.py

feat: label_nodes removed

---

Pipfile
Pipfile.lock
docs/configuration.md
license_sh/commands/run_license_sh.py
license_sh/config.py
license_sh/helpers.py
license_sh/types/configuration.py
tests/test_helpers.py

feat: override license

---

license_sh/analyze/maven.py

fix: maven analyze error
